CC=g++-4.6
CFLAGS=-Wall -fopenmp -std=c++0x -O3
LIB=-lboost_system -lboost_filesystem -lboost_date_time -lgomp -lgsl -lgslcblas -lmatio -larmadillo -lblas -llapack -lredsvd -lsuperlu -larpack -lgfortran -lgfortranbegin -lnsl
